export const ROUTERS = {
	MAIN: "/",
	ABOUT: "/about",
	DELIVERY: "/delivery",
	CONTACTS: "/contacts",
	CATALOG: "/catalog",
	PRODUCT: "/product",
	PRODUCT_BY_ID: (id: string) => `/product/${id}`,
	CART: "/cart",
	PROFILE: "/profile",
	LOGIN: "/login",
	REGISTRATION: "/registration",
	RETURNS: "/returns",
	ORDERS: "/profile/orders",
	FAVORITES: "/profile/favorites",
	SETTINGS: "/profile/settings",
	TERMS: "/terms",
	PRIVACY: "/privacy",
};
